### ISSUE TITLE
indiweb not starting

### ISSUE THREAD

**Issue by Trigger-broom-289** [knro/indiwebmanager#17]
Hello,

I have a thread opened but I cannot solve it, so I'm opening up a bug report.
http://indilib.org/forum/embedded-indi/2947-indi-web-v-not-starting.html

`root@heidenrod-obs:/# indi-web 
Traceback (most recent call last):
  File "/usr/local/bin/indi-web", line 7, in <module>
    from indiweb.main import main
  File "/usr/local/lib/python3.5/dist-packages/indiweb/main.py", line 49, in <module>
    collection = DriverCollection(args.xmldir)
  File "/usr/local/lib/python3.5/dist-packages/indiweb/driver.py", line 30, in __init__
    self.parse_drivers()
  File "/usr/local/lib/python3.5/dist-packages/indiweb/driver.py", line 43, in parse_drivers
    family = group.attrib['group']
KeyError: 'group'
root@heidenrod-obs:/#`

I've tried under python 2.7 too, same issue.

thanks

**Comment by Trigger-broom-289** [comment]
issue was with the xml formatting of my custom drivers. Case solved, please indi forum link from above.
