### ISSUE TITLE
Internal Server Error when loading web manager

### ISSUE THREAD

**Issue by onlinejudge95** [knro/indiwebmanager#60]
I have installed INDI server and related packages on my raspberry pi. I am successfully able to install the web manager and run it in standalone mode. When I open the URL in my browser I receive the following error.

![Screenshot from 2024-09-23 11-33-12](https://github.com/user-attachments/assets/76a96f08-0377-461c-b135-3b71b14244e8)

On the terminal i receive the following logs
```
2024-09-23 11:35:28,346 - DEBUG: command line arguments: {'indi_port': 7624, 'port': 8624, 'host': '0.0.0.0', 'fifo': '/tmp/indiFIFO', 'conf': '/home/onlinejudge95/.indi', 'xmldir': '/usr/share/indi/', 'verbose': True, 'logfile': None, 'server': 'standalone'}
2024-09-23 11:35:28,358 - INFO: using Bottle as standalone server
Traceback (most recent call last):
  File "/home/onlinejudge95/.local/bin/bottle.py", line 994, in _handle
    out = route.call(**args)
  File "/home/onlinejudge95/.local/bin/bottle.py", line 2024, in wrapper
    rv = callback(*a, **ka)
  File "/home/onlinejudge95/.local/lib/python3.9/site-packages/indiweb/main.py", line 140, in main_form
    return template(os.path.join(views_path, 'form.tpl'), profiles=profiles,
  File "/home/onlinejudge95/.local/bin/bottle.py", line 4492, in template
    TEMPLATES[tplid] = adapter(name=tpl, lookup=lookup, **settings)
  File "/home/onlinejudge95/.local/bin/bottle.py", line 4075, in __init__
    self.filename = self.search(self.name, self.lookup)
  File "/home/onlinejudge95/.local/bin/bottle.py", line 4090, in search
    raise depr(0, 12, "Use of absolute path for template name.",
TypeError: exceptions must derive from BaseException
```

**Comment by onlinejudge95** [comment]
This is fixed by #61
