### ISSUE TITLE
Error in bottle.py after URL call

### ISSUE THREAD

**Issue by neurons9** [knro/indiwebmanager#66]
I get the following error message as soon as the URL is called up in the browser:

2024-12-30 22:53:00,228 - DEBUG: command line arguments: {'indi_port': 7624, 'port': 8624, 'host': '0.0.0.0', 'fifo': '/tmp/indiFIFO', 'conf': '/home/teleskop/.indi', 'xmldir': '/usr/share/indi/', 'verbose': True, 'logfile': None, 'server': 'standalone'}
2024-12-30 22:53:00,231 - INFO: using Bottle as standalone server
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 995, in _handle
    out = route.call(**args)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/bottle.py", line 2025, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/indiweb/main.py", line 140, in main_form
    return template(os.path.join(views_path, 'form.tpl'), profiles=profiles,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/bottle.py", line 4493, in template
    TEMPLATES[tplid] = adapter(name=tpl, lookup=lookup, **settings)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/bottle.py", line 4076, in __init__
    self.filename = self.search(self.name, self.lookup)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/bottle.py", line 4091, in search
    raise depr(0, 12, "Use of absolute path for template name.",
DeprecationWarning: Warning: Use of deprecated feature or API. (Deprecated in Bottle-0.12)
Cause: Use of absolute path for template name.
Fix: Refer to templates with names or paths relative to the lookup path.

System: Raspberry Pi 5 with Bookworm. I have tested both a virtual environment and a system-wide installation with the same result

**Comment by samubd** [comment]
I have the same issue. 
I'm using a Dell XPs13 PC with the following OS: 
NAME="Zorin OS"
VERSION="16.3"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 16.3"
VERSION_ID="16"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by bobb16** [comment]
Hi,
it works for me with python version 3.8.10 and bottle version 0.12.25.
Good luck.

**Comment by FreyaAmiga** [comment]
Here same issue with bottle 0.13.2 and python 3.12.3 (ubuntu version 24.04).

**Comment by felixgonsug** [comment]
#67 i found a workarround explained in this issue
